id: quiz_hooks_benefits
learningObjectives:
  - Identify the main benefits of using hooks in React.
hints:
  - Review key benefits in the [React Hooks
    overview](https://reactjs.org/docs/hooks-overview.html).
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Let's test your knowledge! What are the main benefits of using hooks in
              React?
          - text: Choose wisely and let your understanding shine!
    - actionId: quiz_message
      name: quiz
      params:
        person: lucca
        options:
          - They let you use state and other React features without writing a
            class.
          - They force you to mutate state only in class components.
          - They complicate React code and introduce complex lifecycle methods.
          - They only work with Redux, limiting their use.
trigger:
  type: chat_form_submitted
  flowNode:
    switch:
      key: ${formSubmission}
      cases:
        A:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Nailed it! This is one of the primary reasons hooks are a hit in modern
                      React.
            - actionId: finish_step
        B:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Oops! Hooks do the opposite--they allow state management in functional
                      components.
            - actionId: replay_action
              params:
                actionName: quiz
        C:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Not quite! Hooks simplify code by letting you sidestep the intricacies of
                      lifecycle methods in class components.
            - actionId: replay_action
              params:
                actionName: quiz
        D:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Nope! While Redux can complement React hooks, these hooks are designed to
                      work independently.
            - actionId: replay_action
              params:
                actionName: quiz
